sudo: false
language: node_js
node_js: "10"

script:
  - npm test

after_script:
  - npm run tslint
  - ls -l
  - npm install nyc
  - nyc --reporter=lcov --reporter=text-lcov npm test
  - bash <(curl -s https://codecov.io/bash)
